# Generated by Django 3.2.6 on 2021-08-25 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20210824_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatient',
            name='patient_user',
            field=models.ForeignKey(limit_choices_to={'profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
